services:
  - type: web
    name: kadu1155-portfolio01
    env: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
